import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import NavbarBottom from "@/components/navbar/NavbarBottom";
import Providers from "@/store/Providers";
import NextTopLoader from "nextjs-toploader";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mills project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader/>
        <Providers>
          <Navbar />
          <main className="min-h-[80dvh] md:min-h-[60vh] lg:min-h-[80dvh] relative top-16">
            {children}
          </main>
          <Footer />
          <NavbarBottom />
        </Providers>
      </body>
    </html>
  );
}
